### ISSUE TITLE
Not functional?

### ISSUE THREAD

**Issue by valdr** [MycroftAI/skill-support#13]
I ask my mycroft CLI to send me debug info, and I get a "huh? I don't understand" answer...
May this be related to MyCroft not getting my home.mycroft.ai profile information?

**Comment by KathyReid** [comment]
I also saw this behaviour on; 

* Ubuntu 18.04 LTS
* Mycroft core 18.0.0

![screenshot from 2018-09-17 12-50-29](https://user-images.githubusercontent.com/114158/45604715-98f88380-ba7a-11e8-9d6d-d96ac3f434f5.png)

**Comment by krisgesling** [comment]
We've had significant updates on this Skill since this issue was created so I'll close this for now, but please let us know if you are still having trouble.
